# Generated by Django 4.2.1 on 2023-05-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DOB',
            field=models.DateField(),
        ),
    ]
