# Generated by Django 4.2.1 on 2023-05-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a3h1collegestore', '0002_rename_courses_course'),
        ('order', '0003_alter_order_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a3h1collegestore.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a3h1collegestore.department'),
        ),
    ]
