# Generated by Django 4.2.1 on 2023-05-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a3h1collegestore', '0002_rename_courses_course'),
        ('order', '0004_alter_order_course_alter_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a3h1collegestore.department'),
        ),
    ]
