# Generated by Django 4.2.1 on 2023-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='materials_provide',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('FOR_ENQUIRY', 'For enquiry'), ('PLACE_ORDER', 'Place order'), ('RETURN', 'Return')], max_length=250),
        ),
    ]
