# Generated by Django 4.2.1 on 2023-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_materials_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='materials_needed',
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.CharField(blank=True, choices=[('TEXT_BOOK', 'Text book'), ('NOTE_BOOK', 'Notebook'), ('PEN', 'Pen'), ('QUESTION_PAPER', 'Question paper'), ('UNIFORM', 'Uniform'), ('GIFT_CARD', 'Gift card')], default='pen', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
