# Generated by Django 4.2.1 on 2023-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_materials_needed_order_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='materials',
            field=models.TextField(blank=True, default='pen', null=True),
        ),
    ]
