# Generated by Django 4.2.1 on 2023-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_age_alter_order_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
