# Generated by Django 4.2.1 on 2023-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
