# Generated by Django 4.2.1 on 2023-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='materials',
            field=models.CharField(choices=[('TEXT_BOOK', 'Text book'), ('NOTE_BOOK', 'Notebook'), ('PEN', 'Pen'), ('QUESTION_PAPER', 'Question paper'), ('UNIFORM', 'Uniform'), ('GIFT_CARD', 'Gift card')], max_length=250),
        ),
    ]
