# Generated by Django 4.2.1 on 2023-05-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_materials_alter_order_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
