# Generated by Django 4.2.1 on 2023-05-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a3h1collegestore', '0003_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
